declare const styles: {
  readonly item: string;
  readonly completed: string;
  readonly editing: string;
  readonly checkbox: string;
  readonly checkCircle: string;
  readonly checkCircleActive: string;
  readonly content: string;
  readonly text: string;
  readonly dueDate: string;
  readonly dueDateOverdue: string;
  readonly dueDateToday: string;
  readonly actions: string;
  readonly editBtn: string;
  readonly deleteBtn: string;
  readonly confirmBtn: string;
  readonly cancelBtn: string;
  readonly editInput: string;
};
export default styles;
